language: php

php:
  - 5.5

# faster builds on new travis setup not using sudo
sudo: false

install:
  - composer self-update && composer --version
# codeception
  - composer global require codeception/codeception
  - composer install

script:
  - codecept run
