language: php

php:
  - 5.5

# faster builds on new travis setup not using sudo
sudo: false

install:
  - composer self-update && composer --version
  - composer global require "fxp/composer-asset-plugin:~1.0"
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
# codeception
  - composer global require codeception/codeception
  - composer install

script:
  - codecept build
  - codecept run
