language: php

php:
  - 5.4
  - 5.5
  - 5.6

# faster builds on new travis setup not using sudo
sudo: false

install:
  - composer self-update && composer --version
  - composer global require "fxp/composer-asset-plugin:~1.0"
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
# codeception
  - travis_retry composer global require "codeception/codeception=2.0.*" "codeception/specify=*" "codeception/verify=*"
  - composer require yiisoft/yii2
  - composer install

script:
  - php vendor/bin/codecept build
  - php vendor/bin/codecept run
