language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - hhvm-nightly

# run build against hhvm but allow them to fail
# http://docs.travis-ci.com/user/build-configuration/#Rows-That-are-Allowed-To-Fail
matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm-nightly
    - php: 7.0

# faster builds on new travis setup not using sudo
sudo: false

install:
  - composer self-update && composer --version
  - composer global require "fxp/composer-asset-plugin:~1.0"
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
# codeception
  - composer global require codeception/codeception
  - composer install

script:
  - codecept build
  - codecept run
